name: Build APK

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Verify Flutter installation
        run: |
          flutter --version
          flutter doctor -v

      - name: Install dependencies
        run: |
          echo "Installing Flutter dependencies..."
          flutter pub get
          echo "Dependencies installed successfully"

      - name: Build release APK
        run: |
          echo "Starting APK build..."
          flutter build apk --release --verbose
          echo "APK build completed"
          ls -lh build/app/outputs/flutter-apk/

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_type == 'tag' && format('Aywa-{0}-release', github.ref_name) || format('Aywa-{0}-{1}-release', github.event_name, github.run_number) }}
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 90
 
